# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db7023979d1f4a3d91f42b1a8356201a7e9a03cda5675c990dcabc9dca1b0cd932822a4a7a2f7a88f98f5c28ecbcf6a2c7dd551e3598b099c50430eab773fa1

test:
  secret_key_base: 56ebe2a5d758da82465dfad905f5d5064c92f55acc2959f5a4d32056dbaac2c0e53afae8236f84808cded16a53c7411097ad9dd65b573355ab5f72c5adf1a459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
